### ISSUE TITLE
MVP: Roadmap

### ISSUE THREAD

**Issue by JMitnik** [JMitnik/haas#116]
# Must-have features
### General API

Alerts
- [ ] Deliver alert methods
	- [ ] Deliver alerts via Mail
	- [ ] Deliver alerts via SMS
- [ ] Deliver alerts time-points:
	- [ ] For each time
		- [ ] A user enters a certain range of the root-node
		- [ ] A user enters a certain branch
	- [ ] At certain time-intervals (each month)
		- [] Average of root-node entries

### Dashboard
InteractionsOverview:
- [x] Have a table that shows all interactions (on preview/unfolded state, only the root-node).
	- [x] When unfolded (opened), show all the paths a user went through.
	- [x] Paginate items + Allow ability to filter / sort these interactions
		- [x] When applying filter / sort, go back to first page (and refetch)
- [x] Allow ability to export all interactions (filtered/sorted) to a CSV-friendly format.
- [ ] Provide API-endpoint which can be used to query this data (granted a good token is provided)

ActionOverview (showing our Leaf Nodes, CallToActions are shown here):
- [ ] Have our leaf-nodes below one another (folded so that a user is expected to click on one to edit its contents)
- [ ] Add ability to create one (button on top, close to title)

NodeTypes - Registration
- [ ] Have a checkbox of which fields we expect

NodeTypes - LinkAction (__formerly known as Social Share__):
- [ ] Have preset of link-actions
- [ ] Allow ability to create custom link actions

Authentication + Authorization: add login to user
- [ ] Ensure some paths are gated
- [ ] Have a LoginView

Dashboard statistics:
- [ ] Multi-charts, toggle between average of scores and amount of scores across time
- [ ] Track number of call-to-actions
- [ ] Add something like a word-cloud

### Client
Sharability features
- [x] Generating appropriate URLs for 'client' to be shared (can be transformed into QR codes, etc)

Cookies (GDPR-compliant)
- [ ] Saving cookies about a user on user's device (such as a unique identifier)

Fully navigable
- [x] Back-button

Better bunny interaction:
- [ ] Clearer bunny intent
	- [ ] Swipe visible to demonstrate how it might be used (Framer Motion 	enabled)
	- [ ] Interval with text showing up around bunny (stating to drag / its intent)
- [ ] Prevent early release
	- [ ] "Are you sure" dialogue if bunny is held for less than 5 seconds

Aesthetic: Better designs of elements
- [ ] Buttons
- [ ] Aesthetic: Better design of dialogue-ending

# Nice-to-have features
### Dashboard
Better mobile experience
- [ ] General mobile layout

### Client
Embeddable iframe of client
- [ ] Make it look good on other user's website, as a widget or something

Enhanced progress-bar
- [ ] Have a region pressable, that shows a vertical timeline of which states were traversed (and let the user jump around in there).

Enhanced bunny interaction
- [ ] Animated tween color between bunny's slider state and next state, showing the score big, and then showing next state

Validation:
- [ ] Validate inputs to ensure nothing harmful can slip by.
